version: 2
registries:
  npm-public:
    type: npm-registry
    url: https://registry.npmjs.org
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-public
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "quinnjr"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "quinnjr"
    commit-message:
      prefix: "ci"
